# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-04 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionConstants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_constant', models.IntegerField(blank=True, null=True)),
                ('y_constant', models.IntegerField(blank=True, null=True)),
                ('z_constant', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
